// SPDX-License-Identifier: GPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Hexproof contributors
package org.hexproof.forge;

import com.google.gson.*;
import forge.gui.GuiBase;
import forge.item.PaperCard;
import forge.localinstance.properties.ForgePreferences.FPref;
import forge.model.FModel;
import java.nio.file.*;
import java.util.*;

/** Offline census; candidates may share rules only within one catalog Oracle identity. */
public final class NativePrintingIndex {
    private record Printing(String oracle, String name, String set, String number, PaperCard nativeCard) {}
    private static String baseNumber(String number) {
        return number.replaceFirst("^[a-z]+", "").replaceFirst("[psz★]$", "");
    }

    public static void main(String[] args) throws Exception {
        NativeProfile.create();
        try (NativeGuiBase base = new NativeGuiBase(args[0])) {
            GuiBase.setInterface(base.proxy());
            FModel.initialize(null, prefs -> { prefs.setPref(FPref.DECKGEN_CARDBASED, false); return null; });
            Map<String, List<Printing>> groups = new TreeMap<>();
            for (var element : JsonParser.parseString(Files.readString(Path.of(args[1]))).getAsJsonArray()) {
                var row = element.getAsJsonArray();
                String oracle = row.get(0).getAsString(), name = row.get(1).getAsString();
                String set = row.get(2).getAsString(), number = row.get(3).getAsString();
                PaperCard card = NativeSession.findExactCard(FModel.getMagicDb().getCommonCards(), name, set, number);
                if (card == null) {
                    var variant = NativeSession.findExactCard(FModel.getMagicDb().getVariantCards(), name, set, number);
                    if (variant != null && variant.getRules().getType().isConspiracy()) card = variant;
                }
                groups.computeIfAbsent(oracle, key -> new ArrayList<>()).add(new Printing(oracle, name, set, number, card));
            }
            List<String> aliases = new ArrayList<>();
            JsonArray unresolved = new JsonArray();
            int exact = 0;
            for (var group : groups.values()) {
                for (var printing : group) {
                    if (printing.nativeCard() != null) { exact++; continue; }
                    var parents = group.stream().filter(parent -> parent.nativeCard() != null
                            && parent.name().equals(printing.name()) && !parent.nativeCard().getRules().isUnsupported()
                            && !parent.nativeCard().getRules().hasFunctionalVariants()).sorted(Comparator
                            .comparing((Printing parent) -> !parent.set().equals(printing.set()))
                            .thenComparing(parent -> !(printing.set().matches("P[A-Z0-9]{3}")
                                && parent.set().equals(printing.set().substring(1))))
                            .thenComparing(parent -> !baseNumber(printing.number()).equals(parent.number()))
                            .thenComparing(Printing::set).thenComparing(Printing::number)).toList();
                    if (parents.isEmpty()) {
                        JsonArray row = new JsonArray();
                        for (String field : List.of(printing.name(), printing.set(), printing.number())) row.add(field);
                        unresolved.add(row);
                        continue;
                    }
                    PaperCard parent = parents.get(0).nativeCard();
                    aliases.add(String.join("\t", printing.name(), printing.set(), printing.number(),
                            parent.getEdition(), parent.getCollectorNumber()));
                }
            }
            Collections.sort(aliases);
            Files.writeString(Path.of(args[2]), "# SPDX-License-Identifier: GPL-3.0-or-later\n"
                    + "# SPDX-FileCopyrightText: 2026 Hexproof contributors\n"
                    + "# Generated by tools/forge-printings/generate.py; see printing-aliases.json.\n"
                    + "# name\tcatalog set\tcatalog number\tnative set\tnative number\n"
                    + String.join("\n", aliases) + "\n");
            JsonObject report = new JsonObject();
            report.addProperty("exactPrintings", exact);
            report.addProperty("aliasedPrintings", aliases.size());
            report.addProperty("unresolvedPrintings", unresolved.size());
            report.add("unresolved", unresolved);
            Files.writeString(Path.of(args[3]), new GsonBuilder().setPrettyPrinting().create().toJson(report) + "\n");
        }
        System.exit(0);
    }
}
