#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-only
# SPDX-FileCopyrightText: 2026 Hexproof contributors

"""Generate stable Go and Qt wire constants from the Hexproof v1 schema."""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path

from payload_go_structs import verify_go_payload_structs
from payload_schema import (
    load_payload_schema,
    verify_payload_fixtures,
    verify_qt_payload_builders,
)

STABLE_PREFIXES = (
    "Type",
    "Err",
    "Format",
    "DeckFormat",
    "Role",
    "RoomPhase",
    "CardLoad",
    "GamePhase",
    "Zone",
    "MatchBO",
    "LibraryDestination",
    "PlayerCounter",
    "ArrowKind",
    "ResponseStatus",
    "SideboardZone",
    "Protocol",
)
NAME_RE = re.compile(r"^[A-Z][A-Za-z0-9]*$")


@dataclass(frozen=True)
class WireConstant:
    name: str
    value: str


def load_schema(root: Path) -> list[WireConstant]:
    schema_path = root / "protocol/v1/wire-schema.json"
    data = json.loads(schema_path.read_text(encoding="utf-8"))
    if data.get("schemaVersion") != 1:
        raise ValueError("wire schema version must be 1")
    raw_constants = data.get("constants")
    if not isinstance(raw_constants, list) or not raw_constants:
        raise ValueError("wire schema constants must be a non-empty list")

    constants: list[WireConstant] = []
    seen_names: set[str] = set()
    for index, raw in enumerate(raw_constants):
        if not isinstance(raw, dict):
            raise ValueError(f"constant #{index} must be an object")
        name = raw.get("name")
        value = raw.get("value")
        if not isinstance(name, str) or not NAME_RE.fullmatch(name):
            raise ValueError(f"invalid constant name at #{index}: {name!r}")
        if not name.startswith(STABLE_PREFIXES):
            raise ValueError(f"constant {name} does not use a stable prefix")
        if not isinstance(value, str) or not value:
            raise ValueError(f"constant {name} must have a non-empty string value")
        if name in seen_names:
            raise ValueError(f"duplicate constant name: {name}")
        seen_names.add(name)
        constants.append(WireConstant(name, value))

    protocol = data.get("protocol")
    protocol_constant = next((item.value for item in constants if item.name == "ProtocolVersion"), None)
    if protocol != protocol_constant:
        raise ValueError(
            f"schema protocol {protocol!r} does not match ProtocolVersion {protocol_constant!r}"
        )
    return constants


def go_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def cpp_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def render_go(constants: list[WireConstant]) -> str:
    width = max(len(item.name) for item in constants)
    lines = [
        "// SPDX-License-Identifier: GPL-2.0-only",
        "// SPDX-FileCopyrightText: 2026 Hexproof contributors",
        "",
        "// Code generated by tools/protocol_codegen.py; DO NOT EDIT.",
        "",
        "package protocol",
        "",
        "const (",
    ]
    for item in constants:
        lines.append(f"\t{item.name:<{width}} = {go_string(item.value)}")
    lines.extend([")", ""])
    return "\n".join(lines)


def render_cpp(constants: list[WireConstant]) -> str:
    lines = [
        "// SPDX-License-Identifier: GPL-2.0-only",
        "// SPDX-FileCopyrightText: 2026 Hexproof contributors",
        "",
        "// Code generated by tools/protocol_codegen.py; DO NOT EDIT.",
        "",
        "#pragma once",
        "",
        "#include <QString>",
        "",
        "namespace hexproof::protocol {",
        "",
    ]
    for item in constants:
        declaration = (
            f'inline const QString k{item.name} = '
            f'QStringLiteral("{cpp_string(item.value)}");'
        )
        if len(declaration) <= 100:
            lines.append(declaration)
        else:
            lines.extend(
                [
                    f"inline const QString k{item.name} =",
                    f'    QStringLiteral("{cpp_string(item.value)}");',
                ]
            )
    lines.extend(["", "} // namespace hexproof::protocol", ""])
    return "\n".join(lines)


def generated_outputs(root: Path, constants: list[WireConstant]) -> dict[Path, str]:
    return {
        root / "apps/server/internal/protocol/wire_constants_generated.go": render_go(constants),
        root / "apps/client-qt/src/protocol/WireConstantsGenerated.h": render_cpp(constants),
    }


def verify_fixtures(root: Path, constants: list[WireConstant]) -> list[str]:
    message_types = {item.value for item in constants if item.name.startswith("Type")}
    problems: list[str] = []
    for path in sorted((root / "testdata/protocol/v1").glob("*.json")):
        try:
            payload = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as error:
            problems.append(f"{path.relative_to(root)}: invalid JSON: {error}")
            continue
        message_type = payload.get("type") if isinstance(payload, dict) else None
        if not isinstance(message_type, str):
            problems.append(f"{path.relative_to(root)}: missing top-level string type")
        elif message_type not in message_types:
            problems.append(
                f"{path.relative_to(root)}: unknown message type {message_type!r}"
            )
    return problems


def run(root: Path, check: bool) -> int:
    try:
        constants = load_schema(root)
        message_types = {item.value for item in constants if item.name.startswith("Type")}
        payload_schema = load_payload_schema(root, message_types)
        if payload_schema.protocol != next(
            item.value for item in constants if item.name == "ProtocolVersion"
        ):
            raise ValueError("payload schema protocol does not match wire schema")
    except (OSError, json.JSONDecodeError, ValueError) as error:
        print(f"protocol code generation failed: {error}", file=sys.stderr)
        return 2

    problems = verify_fixtures(root, constants)
    problems.extend(verify_payload_fixtures(root, payload_schema))
    problems.extend(verify_go_payload_structs(root, payload_schema))
    problems.extend(verify_qt_payload_builders(root, payload_schema))
    outputs = generated_outputs(root, constants)
    for path, expected in outputs.items():
        if check:
            try:
                actual = path.read_text(encoding="utf-8")
            except OSError as error:
                problems.append(f"{path.relative_to(root)}: {error}")
                continue
            if actual != expected:
                problems.append(
                    f"{path.relative_to(root)} is stale; run python3 tools/protocol_codegen.py"
                )
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected, encoding="utf-8")

    if problems:
        print("protocol schema validation failed:", file=sys.stderr)
        for problem in problems:
            print(f"  - {problem}", file=sys.stderr)
        return 1
    action = "checked" if check else "generated"
    print(
        f"protocol schema {action}: {len(constants)} stable constants, "
        f"{len(payload_schema.messages)} payloads"
    )
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    return run(args.root.resolve(), args.check)


if __name__ == "__main__":
    raise SystemExit(main())
